services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=openpgpwd
      - POSTGRES_USER=openpg
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    expose:
      - "8069"
      - "8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons # Nơi bạn code module Travel
      - ./config:/etc/odoo # Để tùy chỉnh file odoo.conf
    environment:
      - HOST=db
      - USER=openpg
      - PASSWORD=openpgpwd

  odoo-proxy:
    image: nginx:1.27-alpine
    depends_on:
      - odoo
    ports:
      - "8070:80"
    volumes:
      - ./config/nginx-odoo.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  odoo-db-data:
  odoo-web-data: